# Generated by Django 4.2 on 2024-02-26 08:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mein', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='information',
            old_name='addres',
            new_name='address',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='uzer',
            new_name='user',
        ),
    ]
